In [2]:
import pandas as pd
import requests
from datetime import datetime
import time

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from IPython.display import JSON

In [5]:
columns = [
    'id', 'brand', 'source', 'text', 'url', 
    'timestamp', 'sentiment', 'topic', 'urgency'
]

brand_mentions_df = pd.DataFrame(columns=columns)

In [6]:
brand_mentions_df

Empty DataFrame
Columns: [id, brand, source, text, url, timestamp, sentiment, topic, urgency]
Index: []

In [7]:
response = requests.get("https://hn.algolia.com/api/v1/search_by_date?query=OpenAI&tags=comment&hitsPerPage=5").json()
response

{'exhaustive': {'nbHits': False, 'typo': False},
 'exhaustiveNbHits': False,
 'exhaustiveTypo': False,
 'hits': [{'_highlightResult': {'author': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'peterbell_nyc'},
    'comment_text': {'fullyHighlighted': False,
     'matchLevel': 'full',
     'matchedWords': ['openai'],
     'value': "Pi is a nice multi-agent wrapper. I use it to wrap my <em>OpenAI</em> max plan calls and my API calls. It takes care of some of the agent plumbing - still need sandbox, orchestrator, compounding, context, evals, etc but it's a nice component."},
    'story_title': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'Apache Burr: Build reliable AI agents and applications'},
    'story_url': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'https://burr.apache.org/'}},
   '_tags': ['comment', 'author_peterbell_nyc', 'story_48477400'],
   'author': 'peterbell_nyc',
   'comment_text': 'Pi is a nice multi-agent wrapper. I use it to wrap my OpenAI max plan calls and my API calls. It takes care of some of the agent plumbing - still need sandbox, orchestrator, compounding, context, evals, etc but it&#x27;s a nice component.',
   'created_at': '2026-06-10T17:31:02Z',
   'created_at_i': 1781112662,
   'objectID': '48479710',
   'parent_id': 48479380,
   'story_id': 48477400,
   'story_title': 'Apache Burr: Build reliable AI agents and applications',
   'story_url': 'https://burr.apache.org/',
   'updated_at': '2026-06-10T17:31:26Z'},
  {'_highlightResult': {'author': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'peterbell_nyc'},
    'comment_text': {'fullyHighlighted': False,
     'matchLevel': 'full',
     'matchedWords': ['openai'],
     'value': "For me the heart of an agentic system is NOT using agents (except when you really have to). Components of a working system include:\n- Pipelines/recipes to describe multi-step flows (deterministic, agentic and HiTL steps), loops, conditionals, exit-on's for max loop iteractions, etc\n- The logistics to actually run the model and HiTL steps reliably across multiple agent worker pools\n- Management and delivery (and security/governance and permissioning) of thick skills with code to do as much as possible \n- Context management so the right agents have the right context for the right sessions at the right time\n- Project management - ability to store and access tickets, dependencies, track progress, restart stuck ticket claims, etc\n- Transcript saving, memory features and dreaming/compounding capabilities so the agents continue to learn from each session\n- o11y for understanding whats happening, tracking costs and usages, etc\n- Evals and auto-tuning of prompts so you can go cross model provider and also lock to a model version so you can do an ROI on each model version upgrade\n- Sandboxes for running the actual model sessions<p>Don't need to get it all from one vendor, but that feels to me like the toolkit and for most use cases I'd argue:\n- Don't limit yourself to a single model provider (anthropic, <em>openai</em>, etc)\n- Own your context\n- Own your compounding"},
    'story_title': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'Apache Burr: Build reliable AI agents and applications'},
    'story_url': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'https://burr.apache.org/'}},
   '_tags': ['comment', 'author_peterbell_nyc', 'story_48477400'],
   'author': 'peterbell_nyc',
   'comment_text': 'For me the heart of an agentic system is NOT using agents (except when you really have to). Components of a working system include:\n- Pipelines&#x2F;recipes to describe multi-step flows (deterministic, agentic and HiTL steps), loops, conditionals, exit-on&#x27;s for max loop iteractions, etc\n- The logistics to actually run the model and HiTL steps reliably across multiple agent worker pools\n- Management and delivery (and security&#x2F;governance and permissioning) of thick skills with code to do as much as possible \n- Context management so the right agents have the right context for the right sessions at the right time\n- Project management - ability to store and access tickets, dependencies, track progress, restart stuck ticket claims, etc\n- Transcript saving, memory features and dreaming&#x2F;compounding capabilities so the agents continue to learn from each session\n- o11y for understanding whats happening, tracking costs and usages, etc\n- Evals and auto-tuning of prompts so you can go cross model provider and also lock to a model version so you can do an ROI on each model version upgrade\n- Sandboxes for running the actual model sessions<p>Don&#x27;t need to get it all from one vendor, but that feels to me like the toolkit and for most use cases I&#x27;d argue:\n- Don&#x27;t limit yourself to a single model provider (anthropic, openai, etc)\n- Own your context\n- Own your compounding',
   'created_at': '2026-06-10T17:28:10Z',
   'created_at_i': 1781112490,
   'objectID': '48479655',
   'parent_id': 48478157,
   'story_id': 48477400,
   'story_title': 'Apache Burr: Build reliable AI agents and applications',
   'story_url': 'https://burr.apache.org/',
   'updated_at': '2026-06-10T17:35:12Z'},
  {'_highlightResult': {'author': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'unsungNovelty'},
    'comment_text': {'fullyHighlighted': False,
     'matchLevel': 'full',
     'matchedWords': ['openai'],
     'value': 'I still to this day is baffled by all the idiot geniuses who thought it was OK to have &quot;Please enable javascript&quot; when <em>openi</em>ng a website without JS enabled. A good chunk in many pages are just static content. You should be able to render HTML. Ashte!'},
    'story_title': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'Building an HTML-first site doubled our users overnight'},
    'story_url': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'https://mohkohn.co.uk/writing/html-first/'}},
   '_tags': ['comment', 'author_unsungNovelty', 'story_48475483'],
   'author': 'unsungNovelty',
   'comment_text': 'I still to this day is baffled by all the idiot geniuses who thought it was OK to have &quot;Please enable javascript&quot; when opening a website without JS enabled. A good chunk in many pages are just static content. You should be able to render HTML. Ashte!',
   'created_at': '2026-06-10T17:21:44Z',
   'created_at_i': 1781112104,
   'objectID': '48479568',
   'parent_id': 48475483,
   'story_id': 48475483,
   'story_title': 'Building an HTML-first site doubled our users overnight',
   'story_url': 'https://mohkohn.co.uk/writing/html-first/',
   'updated_at': '2026-06-10T17:28:10Z'},
  {'_highlightResult': {'author': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'baq'},
    'comment_text': {'fullyHighlighted': False,
     'matchLevel': 'full',
     'matchedWords': ['openai'],
     'value': '<em>OpenAI</em>, Anthropic and Google serve models, but approximately all of their combined output ends up on github.'},
    'story_title': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'GitHub Authentication issues related to API requests'},
    'story_url': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'https://www.githubstatus.com/incidents/fcj3088jg1wx'}},
   '_tags': ['comment', 'author_baq', 'story_48477851'],
   'author': 'baq',
   'comment_text': 'OpenAI, Anthropic and Google serve models, but approximately all of their combined output ends up on github.',
   'created_at': '2026-06-10T16:47:59Z',
   'created_at_i': 1781110079,
   'objectID': '48479062',
   'parent_id': 48478893,
   'story_id': 48477851,
   'story_title': 'GitHub Authentication issues related to API requests',
   'story_url': 'https://www.githubstatus.com/incidents/fcj3088jg1wx',
   'updated_at': '2026-06-10T17:30:12Z'},
  {'_highlightResult': {'author': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'masonwan'},
    'comment_text': {'fullyHighlighted': False,
     'matchLevel': 'full',
     'matchedWords': ['openai'],
     'value': 'I guess the same rules also applied to <em>OpenAI</em>, Anthropic, Microsoft, Meta, and Amazon?'},
    'story_title': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'German ruling declares Google liable for false answers in AI Overviews'},
    'story_url': {'matchLevel': 'none',
     'matchedWords': [],
     'value': 'https://the-decoder.com/landmark-german-ruling-declares-googles-ai-overviews-are-googles-own-words-and-makes-it-liable-for-false-answers/'}},
   '_tags': ['comment', 'author_masonwan', 'story_48470248'],
   'author': 'masonwan',
   'children': [48479402],
   'comment_text': 'I guess the same rules also applied to OpenAI, Anthropic, Microsoft, Meta, and Amazon?',
   'created_at': '2026-06-10T16:41:56Z',
   'created_at_i': 1781109716,
   'objectID': '48478966',
   'parent_id': 48470248,
   'story_id': 48470248,
   'story_title': 'German ruling declares Google liable for false answers in AI Overviews',
   'story_url': 'https://the-decoder.com/landmark-german-ruling-declares-googles-ai-overviews-are-googles-own-words-and-makes-it-liable-for-false-answers/',
   'updated_at': '2026-06-10T17:10:13Z'}],
 'hitsPerPage': 5,
 'nbHits': 398167,
 'nbPages': 200,
 'page': 0,
 'params': 'query=OpenAI&tags=comment&hitsPerPage=5&advancedSyntax=true&analyticsTags=backend',
 'processingTimeMS': 14,
 'processingTimingsMS': {'_request': {'roundTrip': 22},
  'fetch': {'query': 3, 'scanning': 10, 'total': 14},
  'total': 14},
 'query': 'OpenAI',
 'serverTimeMS': 15}

In [8]:
response.get('hits')[1]

{'_highlightResult': {'author': {'matchLevel': 'none',
   'matchedWords': [],
   'value': 'peterbell_nyc'},
  'comment_text': {'fullyHighlighted': False,
   'matchLevel': 'full',
   'matchedWords': ['openai'],
   'value': "For me the heart of an agentic system is NOT using agents (except when you really have to). Components of a working system include:\n- Pipelines/recipes to describe multi-step flows (deterministic, agentic and HiTL steps), loops, conditionals, exit-on's for max loop iteractions, etc\n- The logistics to actually run the model and HiTL steps reliably across multiple agent worker pools\n- Management and delivery (and security/governance and permissioning) of thick skills with code to do as much as possible \n- Context management so the right agents have the right context for the right sessions at the right time\n- Project management - ability to store and access tickets, dependencies, track progress, restart stuck ticket claims, etc\n- Transcript saving, memory features and dreaming/compounding capabilities so the agents continue to learn from each session\n- o11y for understanding whats happening, tracking costs and usages, etc\n- Evals and auto-tuning of prompts so you can go cross model provider and also lock to a model version so you can do an ROI on each model version upgrade\n- Sandboxes for running the actual model sessions<p>Don't need to get it all from one vendor, but that feels to me like the toolkit and for most use cases I'd argue:\n- Don't limit yourself to a single model provider (anthropic, <em>openai</em>, etc)\n- Own your context\n- Own your compounding"},
  'story_title': {'matchLevel': 'none',
   'matchedWords': [],
   'value': 'Apache Burr: Build reliable AI agents and applications'},
  'story_url': {'matchLevel': 'none',
   'matchedWords': [],
   'value': 'https://burr.apache.org/'}},
 '_tags': ['comment', 'author_peterbell_nyc', 'story_48477400'],
 'author': 'peterbell_nyc',
 'comment_text': 'For me the heart of an agentic system is NOT using agents (except when you really have to). Components of a working system include:\n- Pipelines&#x2F;recipes to describe multi-step flows (deterministic, agentic and HiTL steps), loops, conditionals, exit-on&#x27;s for max loop iteractions, etc\n- The logistics to actually run the model and HiTL steps reliably across multiple agent worker pools\n- Management and delivery (and security&#x2F;governance and permissioning) of thick skills with code to do as much as possible \n- Context management so the right agents have the right context for the right sessions at the right time\n- Project management - ability to store and access tickets, dependencies, track progress, restart stuck ticket claims, etc\n- Transcript saving, memory features and dreaming&#x2F;compounding capabilities so the agents continue to learn from each session\n- o11y for understanding whats happening, tracking costs and usages, etc\n- Evals and auto-tuning of prompts so you can go cross model provider and also lock to a model version so you can do an ROI on each model version upgrade\n- Sandboxes for running the actual model sessions<p>Don&#x27;t need to get it all from one vendor, but that feels to me like the toolkit and for most use cases I&#x27;d argue:\n- Don&#x27;t limit yourself to a single model provider (anthropic, openai, etc)\n- Own your context\n- Own your compounding',
 'created_at': '2026-06-10T17:28:10Z',
 'created_at_i': 1781112490,
 'objectID': '48479655',
 'parent_id': 48478157,
 'story_id': 48477400,
 'story_title': 'Apache Burr: Build reliable AI agents and applications',
 'story_url': 'https://burr.apache.org/',
 'updated_at': '2026-06-10T17:35:12Z'}

In [9]:
JSON(response)

In [10]:
extracted_data = []
for hit in response.get('hits',[]):
    extracted_data.append({
        'id': hit.get('objectID'),
        'brand': 'OpenAI',
        'source': 'Hacker News',
        'text': hit.get('comment_text'),
        'url': f"https://news.ycombinator.com/item?id={hit.get('objectID')}",
        'timestamp': datetime.fromtimestamp(hit.get('created_at_i')),
        'sentiment': None,
        'topic': None,
        'urgency': None
    })

brand_mentions_df = pd.DataFrame(extracted_data)

In [11]:
brand_mentions_df

,id,brand,source,text,url,timestamp,sentiment,topic,urgency
0,48479710,OpenAI,Hacker News,Pi is a nice multi-agent wrapper. I use it to ...,https://news.ycombinator.com/item?id=48479710,2026-06-10 23:01:02,None,None,None
1,48479655,OpenAI,Hacker News,For me the heart of an agentic system is NOT u...,https://news.ycombinator.com/item?id=48479655,2026-06-10 22:58:10,None,None,None
2,48479568,OpenAI,Hacker News,I still to this day is baffled by all the idio...,https://news.ycombinator.com/item?id=48479568,2026-06-10 22:51:44,None,None,None
3,48479062,OpenAI,Hacker News,"OpenAI, Anthropic and Google serve models, but...",https://news.ycombinator.com/item?id=48479062,2026-06-10 22:17:59,None,None,None
4,48478966,OpenAI,Hacker News,"I guess the same rules also applied to OpenAI,...",https://news.ycombinator.com/item?id=48478966,2026-06-10 22:11:56,None,None,None

In [12]:
brand_mentions_df["text"][1]

'For me the heart of an agentic system is NOT using agents (except when you really have to). Components of a working system include:\n- Pipelines&#x2F;recipes to describe multi-step flows (deterministic, agentic and HiTL steps), loops, conditionals, exit-on&#x27;s for max loop iteractions, etc\n- The logistics to actually run the model and HiTL steps reliably across multiple agent worker pools\n- Management and delivery (and security&#x2F;governance and permissioning) of thick skills with code to do as much as possible \n- Context management so the right agents have the right context for the right sessions at the right time\n- Project management - ability to store and access tickets, dependencies, track progress, restart stuck ticket claims, etc\n- Transcript saving, memory features and dreaming&#x2F;compounding capabilities so the agents continue to learn from each session\n- o11y for understanding whats happening, tracking costs and usages, etc\n- Evals and auto-tuning of prompts so you can go cross model provider and also lock to a model version so you can do an ROI on each model version upgrade\n- Sandboxes for running the actual model sessions<p>Don&#x27;t need to get it all from one vendor, but that feels to me like the toolkit and for most use cases I&#x27;d argue:\n- Don&#x27;t limit yourself to a single model provider (anthropic, openai, etc)\n- Own your context\n- Own your compounding'

In [13]:
import html

brand_mentions_df["text"] = brand_mentions_df["text"].str.replace(r'<[^<>]*>', ' ', regex=True)
brand_mentions_df["text"] = brand_mentions_df["text"].apply(html.unescape)
brand_mentions_df["text"] = brand_mentions_df["text"].str.replace(r'\s+', ' ', regex=True).str.strip()

In [14]:
brand_mentions_df

,id,brand,source,text,url,timestamp,sentiment,topic,urgency
0,48479710,OpenAI,Hacker News,Pi is a nice multi-agent wrapper. I use it to ...,https://news.ycombinator.com/item?id=48479710,2026-06-10 23:01:02,None,None,None
1,48479655,OpenAI,Hacker News,For me the heart of an agentic system is NOT u...,https://news.ycombinator.com/item?id=48479655,2026-06-10 22:58:10,None,None,None
2,48479568,OpenAI,Hacker News,I still to this day is baffled by all the idio...,https://news.ycombinator.com/item?id=48479568,2026-06-10 22:51:44,None,None,None
3,48479062,OpenAI,Hacker News,"OpenAI, Anthropic and Google serve models, but...",https://news.ycombinator.com/item?id=48479062,2026-06-10 22:17:59,None,None,None
4,48478966,OpenAI,Hacker News,"I guess the same rules also applied to OpenAI,...",https://news.ycombinator.com/item?id=48478966,2026-06-10 22:11:56,None,None,None

In [15]:
brand_mentions_df["text"][0]

"Pi is a nice multi-agent wrapper. I use it to wrap my OpenAI max plan calls and my API calls. It takes care of some of the agent plumbing - still need sandbox, orchestrator, compounding, context, evals, etc but it's a nice component."

In [33]:
texts = "\n--\n".join(brand_mentions_df[brand_mentions_df['brand'] == 'OpenAI']['text'].tolist())
texts

'Pi is a nice multi-agent wrapper. I use it to wrap my OpenAI max plan calls and my API calls. It takes care of some of the agent plumbing - still need sandbox, orchestrator, compounding, context, evals, etc but it\'s a nice component.\n--\nFor me the heart of an agentic system is NOT using agents (except when you really have to). Components of a working system include: - Pipelines/recipes to describe multi-step flows (deterministic, agentic and HiTL steps), loops, conditionals, exit-on\'s for max loop iteractions, etc - The logistics to actually run the model and HiTL steps reliably across multiple agent worker pools - Management and delivery (and security/governance and permissioning) of thick skills with code to do as much as possible - Context management so the right agents have the right context for the right sessions at the right time - Project management - ability to store and access tickets, dependencies, track progress, restart stuck ticket claims, etc - Transcript saving, memory features and dreaming/compounding capabilities so the agents continue to learn from each session - o11y for understanding whats happening, tracking costs and usages, etc - Evals and auto-tuning of prompts so you can go cross model provider and also lock to a model version so you can do an ROI on each model version upgrade - Sandboxes for running the actual model sessions Don\'t need to get it all from one vendor, but that feels to me like the toolkit and for most use cases I\'d argue: - Don\'t limit yourself to a single model provider (anthropic, openai, etc) - Own your context - Own your compounding\n--\nI still to this day is baffled by all the idiot geniuses who thought it was OK to have "Please enable javascript" when opening a website without JS enabled. A good chunk in many pages are just static content. You should be able to render HTML. Ashte!\n--\nOpenAI, Anthropic and Google serve models, but approximately all of their combined output ends up on github.\n--\nI guess the same rules also applied to OpenAI, Anthropic, Microsoft, Meta, and Amazon?'

In [31]:
brand_mentions_df[brand_mentions_df['brand'] == 'OpenAI']['text'].tolist()

["Pi is a nice multi-agent wrapper. I use it to wrap my OpenAI max plan calls and my API calls. It takes care of some of the agent plumbing - still need sandbox, orchestrator, compounding, context, evals, etc but it's a nice component.",
 "For me the heart of an agentic system is NOT using agents (except when you really have to). Components of a working system include: - Pipelines/recipes to describe multi-step flows (deterministic, agentic and HiTL steps), loops, conditionals, exit-on's for max loop iteractions, etc - The logistics to actually run the model and HiTL steps reliably across multiple agent worker pools - Management and delivery (and security/governance and permissioning) of thick skills with code to do as much as possible - Context management so the right agents have the right context for the right sessions at the right time - Project management - ability to store and access tickets, dependencies, track progress, restart stuck ticket claims, etc - Transcript saving, memory features and dreaming/compounding capabilities so the agents continue to learn from each session - o11y for understanding whats happening, tracking costs and usages, etc - Evals and auto-tuning of prompts so you can go cross model provider and also lock to a model version so you can do an ROI on each model version upgrade - Sandboxes for running the actual model sessions Don't need to get it all from one vendor, but that feels to me like the toolkit and for most use cases I'd argue: - Don't limit yourself to a single model provider (anthropic, openai, etc) - Own your context - Own your compounding",
 'I still to this day is baffled by all the idiot geniuses who thought it was OK to have "Please enable javascript" when opening a website without JS enabled. A good chunk in many pages are just static content. You should be able to render HTML. Ashte!',
 'OpenAI, Anthropic and Google serve models, but approximately all of their combined output ends up on github.',
 'I guess the same rules also applied to OpenAI, Anthropic, Microsoft, Meta, and Amazon?']